from django.urls import path
from .views import (
    HomePageView,Base64DecodeImage,Base64EncodeImage,Base64Decoder,
    Base64Encoder,BcryptGenerator,CloudflareEmailDecoder,ColorConverter,CSSBeautifier,
    EmailChecker,ImageColorPicker,IPaddressLookup,JSONBeautifier,MarkdownEditor,
    MD5Generator,RandomPasswordGenerator,SHAGenerator,SVGtoJPG,SVGtoPNG,
    WhatIsMyHeaders,WordCounter,PrivacyPolicy,TermsAndConditions,DVPhotoTool,ImageCompressor,ImageResizer,URLEncoderDecoder,JWTDecoder,UUIDULIDGenerator,UnixTimestampConverter,RegexTester,TextDiffChecker,QRCodeGenerator,MarkdownHtmlConverter,ImageBackgroundRemover,ImageWatermarker,CSVJSONConverter,CaseConverter,PasswordEntropy,QRCodeScanner,BarcodeGenerator,SubnetCalculator,ExifTool,JWTGenerator,ASCIIArtGenerator,SSLCertificateChecker,HashIdentifier,HSTSChecker,SecurityHeadersChecker,RedirectChainAnalyzer,MorseCodeEncoderDecoder,LeetSpeakConverter,DomainAgeChecker,PDFtoImages
)

app_name = "app_app"

urlpatterns = [

    path("privacy-policy/",PrivacyPolicy.as_view(),name="privacy_policy"),
    path("terms/",TermsAndConditions.as_view(),name="terms"),
    path("dv-photo-tool/",DVPhotoTool.as_view(),name="dv_photo_tool"),
    path("word-counter/",WordCounter.as_view(),name="word_counter"),
    path("what-is-my-headers/",WhatIsMyHeaders.as_view(),name="what_is_my_headers"),
    path("svg-to-png/",SVGtoPNG.as_view(),name="svg_to_png"),
    path("image-compressor/",ImageCompressor.as_view(),name="image_compressor"),
    path("image-resizer/",ImageResizer.as_view(),name="image_resizer"),
    path("url-encoder-decoder/",URLEncoderDecoder.as_view(),name="url_encoder_decoder"),
    path("jwt-decoder/",JWTDecoder.as_view(),name="jwt_decoder"),
    path("uuid-ulid-generator/",UUIDULIDGenerator.as_view(),name="uuid_ulid_generator"),
    path("unix-timestamp-converter/",UnixTimestampConverter.as_view(),name="unix_timestamp_converter"),
    path("regex-tester/",RegexTester.as_view(),name="regex_tester"),
    path("text-diff-checker/",TextDiffChecker.as_view(),name="text_diff_checker"),
    path("qr-code-generator/",QRCodeGenerator.as_view(),name="qr_code_generator"),
    path("markdown-html-converter/",MarkdownHtmlConverter.as_view(),name="markdown_html_converter"),
    path("image-background-remover/",ImageBackgroundRemover.as_view(),name="image_background_remover"),
    path("image-watermarker/",ImageWatermarker.as_view(),name="image_watermarker"),
    path("csv-json-converter/",CSVJSONConverter.as_view(),name="csv_json_converter"),
    path("case-converter/",CaseConverter.as_view(),name="case_converter"),
    path("password-entropy/",PasswordEntropy.as_view(),name="password_entropy"),
    path("qr-code-scanner/",QRCodeScanner.as_view(),name="qr_code_scanner"),
    path("barcode-generator/",BarcodeGenerator.as_view(),name="barcode_generator"),
    path("subnet-calculator/",SubnetCalculator.as_view(),name="subnet_calculator"),
    path("exif-tool/",ExifTool.as_view(),name="exif_tool"),
    path("jwt-generator/",JWTGenerator.as_view(),name="jwt_generator"),
    path("ascii-art-generator/",ASCIIArtGenerator.as_view(),name="ascii_art_generator"),
    path("ssl-certificate-checker/",SSLCertificateChecker.as_view(),name="ssl_certificate_checker"),
    path("hash-identifier/",HashIdentifier.as_view(),name="hash_identifier"),
    path("hsts-checker/",HSTSChecker.as_view(),name="hsts_checker"),
    path("security-headers-checker/",SecurityHeadersChecker.as_view(),name="security_headers_checker"),
    path("redirect-chain-analyzer/",RedirectChainAnalyzer.as_view(),name="redirect_chain_analyzer"),
    path("domain-age-checker/",DomainAgeChecker.as_view(),name="domain_age_checker"),
    path("pdf-to-images/",PDFtoImages.as_view(),name="pdf_to_images"),
    path("morse-code-encoder-decoder/",MorseCodeEncoderDecoder.as_view(),name="morse_code_encoder_decoder"),
    path("leet-speak-converter/",LeetSpeakConverter.as_view(),name="leet_speak_converter"),
    path("svg-to-jpg/",SVGtoJPG.as_view(),name="svg_to_jpg"),
    path("sha-generator/",SHAGenerator.as_view(),name="sha_generator"),
    path("random-password-generator/",RandomPasswordGenerator.as_view(),name="random_password_generator"),
    path("md5-generator/",MD5Generator.as_view(),name="md5_generator"),
    path("markdown-editor/",MarkdownEditor.as_view(),name="markdown_editor"),
    path("json-beautifier/",JSONBeautifier.as_view(),name="json_beautifier"),
    path("ip-address-detail/",IPaddressLookup.as_view(),name="ipaddress_lookup"),
    path("image-color-picker/",ImageColorPicker.as_view(),name="image_color_picker"),
    path("email-checker/",EmailChecker.as_view(),name="email_checker"),
    path("css-beautifier/",CSSBeautifier.as_view(),name="css_beautifier"),
    path("color-converter/",ColorConverter.as_view(),name="color_converter"),
    path("cloudflare-email-decoder/",CloudflareEmailDecoder.as_view(),name="cloudflare_email_decoder"),
    path("bcrypt-generator/",BcryptGenerator.as_view(),name="bcrypt_generator"),
    path("base64-encoder/",Base64Encoder.as_view(),name="base64_encoder"),
    path("base64-decoder/",Base64Decoder.as_view(),name="base64_decoder"),
    path("base64-encode-image/",Base64EncodeImage.as_view(),name="base64_encode_image"),
    path("base64-decode-image/",Base64DecodeImage.as_view(),name="base64_decode_image"),
    path("",HomePageView.as_view(),name="home"),
]